package us.heptet.magewars.domain.game;

/***
 * Possible targets of a card/spell.
 */
public enum TargetType {
    CREATURE,
    LIVING_CREATURE,
    CORPOREAL_CREATURE,
    NONMAGE_CREATURE,
    NONMAGE_LIVING_CREATURE,
    ZONE_OR_OBJECT,
    FORCEMASTER,
    ZONE,
    OBJECT,
    FRIENDLY_SOLDIER_CREATURE,
    MAGE, ARENA, REVEALED_ENCHANTMENT, MAGE_EQUIPMENT, ZONE_BORDER, NONMAGE_CORPOREAL_CREATURE

}
